### ISSUE TITLE
One line for NetworkManager is needed

### ISSUE THREAD

**Issue by way2master** [android10/linux.github.io#1]
Hello,
Thank you for your document. It's a lot helping me. This issue is not a big, but a 'Good to Have'.

[https://linux.fernandocejas.com/docs/how-to/switch-from-network-manager-to-systemd-networkd
](url)
**$ sudo systemctl stop NetworkManager**
$ sudo systemctl disable NetworkManager
$ sudo systemctl enable systemd-networkd 

I added first line with 'stop'. Without that the creation of **symlink of resolv.conf** were blocked, since NetworkManager is still active.

**Comment by android10** [comment]
@way2master I was late here. I apologize since for some reason I have not seen any notification. I will add your suggestion. Thank you very much for your contribution ❤️

**Comment by android10** [comment]
Here is the fix: 

 - https://github.com/android10/linux.github.io/commit/4190ccd1cfa8ad9097d6dc31fb2211d138bad37c

cc @way2master
